<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UA41MGR" failures="2" tests="6" name="com.example.DEMO.TESJO.DemoTesjoApplicationTests" time="19.454" errors="0" timestamp="2021-11-14T22:28:46 GMT-06:00" skipped="0">
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginExitoso" time="4.376"/>
  <system-out/>
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginExitoso" time="3.037"/>
  <system-out/>
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginLockedOutUser" time="3.028">
    <failure message="expected [Epic sadface: Sorry, this user has been loced out.] but found [Epic sadface: Sorry, this user has been locked out.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been loced out.] but found [Epic sadface: Sorry, this user has been locked out.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.example.DEMO.TESJO.DemoTesjoApplicationTests.loginLockedOutUser(DemoTesjoApplicationTests.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- loginLockedOutUser -->
  <system-out/>
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginNoExitoso" time="2.977"/>
  <system-out/>
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginLockedOutUser" time="3.067">
    <failure message="expected [Epic sadface: Sorry, this user has been loced out.] but found [Epic sadface: Sorry, this user has been locked out.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been loced out.] but found [Epic sadface: Sorry, this user has been locked out.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.example.DEMO.TESJO.DemoTesjoApplicationTests.loginLockedOutUser(DemoTesjoApplicationTests.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- loginLockedOutUser -->
  <system-out/>
  <testcase classname="com.example.DEMO.TESJO.DemoTesjoApplicationTests" name="loginNoExitoso" time="2.969"/>
  <system-out/>
</testsuite> <!-- com.example.DEMO.TESJO.DemoTesjoApplicationTests -->
